name: objectx
description: "Extension for Dart's Object: let, letOrNull, String extensions, etc..."
version: 1.0.2
repository: https://github.com/sonnts996/objectx

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  meta: ^1.9.0
  intl: ^0.18.0

dev_dependencies:
  owlet_lints: ^3.0.0
  test: ^1.21.0
