name: objectx
description: "Extension for Dart's Object: let, letOrNull, String extensions, etc..."
version: 1.0.3
repository: https://github.com/sonnts996/objectx

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  meta: '>=1.9.0 <2.0.0'
  intl: '>=0.18.0 <0.20.0'

dev_dependencies:
  owlet_lints: ^4.0.0+1
  test: ^1.25.0
