name: objectx
description: "Extension for Dart's Object: let, letOrNull, String extensions, etc..."
version: 1.0.0+1-dev
repository: https://github.com/sonnts996/objectx

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  meta: ^1.10.0
  intl: ^0.18.1

dev_dependencies:
  owlet_lints: ^3.0.0
  test: ^1.21.0
